// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMediiMaster_BogdanIstrate.Data;

namespace ProjectMediiMaster_BogdanIstrate.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20220107141344_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.AppCustomer", b =>
                {
                    b.Property<int>("AppCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppCustomerId");

                    b.ToTable("AppCustomer");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.Guitar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppCustomerId");

                    b.ToTable("Guitar");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.GuitarOrder", b =>
                {
                    b.Property<int>("GuitarOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppCustomerId")
                        .HasColumnType("int");

                    b.Property<int>("GuitarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GuitarOrderId");

                    b.HasIndex("AppCustomerId");

                    b.HasIndex("GuitarId");

                    b.ToTable("GuitarOrder");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppCustomerId")
                        .HasColumnType("int");

                    b.Property<int>("GuitarId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("AppCustomerId");

                    b.HasIndex("GuitarId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.Guitar", b =>
                {
                    b.HasOne("ProjectMediiMaster_BogdanIstrate.Models.AppCustomer", "AppCustomer")
                        .WithMany("Guitars")
                        .HasForeignKey("AppCustomerId");

                    b.Navigation("AppCustomer");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.GuitarOrder", b =>
                {
                    b.HasOne("ProjectMediiMaster_BogdanIstrate.Models.AppCustomer", "AppCustomer")
                        .WithMany("GuitarOrders")
                        .HasForeignKey("AppCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMediiMaster_BogdanIstrate.Models.Guitar", "Guitar")
                        .WithMany("GuitarOrders")
                        .HasForeignKey("GuitarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppCustomer");

                    b.Navigation("Guitar");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.Review", b =>
                {
                    b.HasOne("ProjectMediiMaster_BogdanIstrate.Models.AppCustomer", "AppCustomer")
                        .WithMany("Reviews")
                        .HasForeignKey("AppCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMediiMaster_BogdanIstrate.Models.Guitar", "Guitar")
                        .WithMany("Reviews")
                        .HasForeignKey("GuitarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppCustomer");

                    b.Navigation("Guitar");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.AppCustomer", b =>
                {
                    b.Navigation("GuitarOrders");

                    b.Navigation("Guitars");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ProjectMediiMaster_BogdanIstrate.Models.Guitar", b =>
                {
                    b.Navigation("GuitarOrders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
